# Generated by Django 4.0.6 on 2022-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.CharField(default=2016, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
